#!/bin/sh

result=$(curl -X POST --data @routes.geojson $data http://geojsonlint.com/validate 2>/dev/null)

if [ "$result" = "{\"status\": \"ok\"}" ]; then
  echo "Valid geoJSON!"
  exit 0
else
  echo "Invalid geoJSON"
  exit 1
fi